apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: onechart
      app.kubernetes.io/instance: github-actions-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: onechart
        app.kubernetes.io/instance: github-actions-example
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: github-actions-example
          image: "ghcr.io/gimlet-io/fosdem-2021:a15eaaf1f0505bc4e1f5d92827492fbe2a72ed18"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
