apiVersion: v1
kind: Service
metadata:
  name: fosdem-2021
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: fosdem-2021
