apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-example
  namespace: my-team
  labels:
    helm.sh/chart: onechart-0.10.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: github-actions-example
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: onechart
      app.kubernetes.io/instance: github-actions-example
  template:
    metadata:
      annotations:
        checksum/config: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
      labels:
        app.kubernetes.io/name: onechart
        app.kubernetes.io/instance: github-actions-example
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: github-actions-example
          securityContext:
            {}
          image: "ghcr.io/gimlet-io/github-actions-example:f6e23717fea3af0cb547413526b6af1b37093110"
          imagePullPolicy: 
          envFrom:
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
      volumes:
