apiVersion: v1
kind: Service
metadata:
  name: github-actions-example
  namespace: my-team
  labels:
    helm.sh/chart: onechart-0.10.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: github-actions-example
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: github-actions-example
